### ISSUE TITLE
Dim Issue

### ISSUE THREAD

**Issue by Z1hanW** [mxu34/prompt-dt#3]
Hi, Mengdi,
very nice work,
however, when I try to run the script using python pdt_main.py --env cheetah_dir.
I got a dim issue, 
```
Traceback (most recent call last):
  File "pdt_main.py", line 281, in <module>
    experiment_mix_env('gym-experiment', variant=vars(args))
  File "pdt_main.py", line 136, in experiment_mix_env
    trainer = PromptSequenceTrainer(
  File "/jet/home/zwangp/prompt-dt/prompt_dt/prompt_seq_trainer.py", line 25, in __init__
    self.prompt = self.get_prompt() # sample prompt data when initialization
  File "/jet/home/zwangp/prompt-dt/prompt_dt/prompt_utils.py", line 125, in fn
    s.append(traj['observations'][si:si + max_len].reshape(1, -1, state_dim))
ValueError: cannot reshape array of size 100 into shape (1,newaxis,17)
```

Is there anything I am missing? Thanks in advance

**Comment by betray12138** [comment]
> Hi, Mengdi, very nice work, however, when I try to run the script using python pdt_main.py --env cheetah_dir. I got a dim issue,
> 
> ```
> Traceback (most recent call last):
>   File "pdt_main.py", line 281, in <module>
>     experiment_mix_env('gym-experiment', variant=vars(args))
>   File "pdt_main.py", line 136, in experiment_mix_env
>     trainer = PromptSequenceTrainer(
>   File "/jet/home/zwangp/prompt-dt/prompt_dt/prompt_seq_trainer.py", line 25, in __init__
>     self.prompt = self.get_prompt() # sample prompt data when initialization
>   File "/jet/home/zwangp/prompt-dt/prompt_dt/prompt_utils.py", line 125, in fn
>     s.append(traj['observations'][si:si + max_len].reshape(1, -1, state_dim))
> ValueError: cannot reshape array of size 100 into shape (1,newaxis,17)
> ```
> 
> Is there anything I am missing? Thanks in advance

Hi, do you solve this problem ? I meet the same now . Could you please give me some advice ?

**Comment by greenjerry** [comment]
I met this problem when I using gym==0.26.0 and I solved it by using gym==0.18.3.
If error "Expected end or semicolon (after version specifier)   opencv-python>=3" occurs, you can refer to [this](https://stackoverflow.com/questions/76129688/why-is-pip-install-gym-failing-with-python-setup-py-egg-info-did-not-run-succ)
